SKASP.WEB/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using SKASP.DOMAIN.Abstract;
using SKASP.DOMAIN.EntitiesModel;

namespace SKASP.WEB.Controllers
{
	/// <summary>
	/// The forum controller.
	/// </summary>
	public class ForumController : Controller
	{
		/// <summary>
		/// The repository.
		/// </summary>
		private readonly IForumRepository repository;

		/// <summary>
		/// Initializes a new instance of the <see cref="ForumController"/> class.
		/// </summary>
		/// <param name="repo">
		/// The repo.
		/// </param>
		public ForumController(IForumRepository repo)
		{
			repository = repo;
		}

		/// <summary>
		/// The themes.
		/// </summary>
		/// <returns>
		/// The <see cref="ActionResult"/>.
		/// </returns>
		[Authorize]
        public ActionResult Themes()
        {
            return View(repository.Themes);
        }

		/// <summary>
		/// The create theme.
		/// </summary>
		/// <param name="item">
		/// The item.
		/// </param>
		/// <returns>
		/// The <see cref="ActionResult"/>.
		/// </returns>
		[Authorize]
		[HttpPost]
		public ActionResult CreateTheme(Theme item)
		{
			if (ModelState.IsValid)
			{
				repository.Themes.AddValue(item);
			}
			return RedirectToAction("Themes");
		}

		/// <summary>
		/// The topics.
		/// </summary>
		/// <param name="id">
		/// The id.
		/// </param>
		/// <returns>
		/// The <see cref="ActionResult"/>.
		/// </returns>
		[Authorize]
		public ActionResult Topics(int id)
		{
			List<Topic> topics = repository.Topics.Repository.Where(x => x.ID == id).ToList();
			return this.View(topics);
		}
    }
}

SKASP.WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SKASP.WEB.Controllers
{
    using SKASP.DOMAIN.Abstract;
    using SKASP.DOMAIN.Concrete;
    using SKASP.DOMAIN.EntitiesModel;

    public class HomeController : Controller
    {
        public int PageSize = 4;

        private IManageable<News> repo;

		public HomeController(IManageable<News> repository)
        {
            repo = repository;
        }

        public ViewResult Default(string id)
        {
            int Id;
            if (id == "All") return this.View(repo);
            else if (int.TryParse(id, out Id))
            {
                return this.View("NewsViewer", this.repo.Repository.First(x => x.ID == Id));
            }
            else
            {
                return this.View(repo);
            }
        }
        [Authorize]
        public ViewResult About()
        {
            return this.View();
        }
    }
}

SKASP.WEB/Views/Home/About.cshtml
@{
	ViewBag.Title = "About";
	Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<div class="hero-unit">
	<div align="center" style="font-family: Calibri; font-size: xx-large; color: #555555">
			About Page
	</div>
	<br/>
	<div align="center">
		<div class="control-group">
			<p class="brand">I am agile ASP.NET Developer from Minsk. I'm trying to change myself everyday, learning new everyday in my life and I hate to spend my time on empty things!</p>
			<img id="AuthorFoto" src="http://cs304213.userapi.com/v304213328/2825/PhdQ_7McEwA.jpg"/>
		</div>
	</div>
	<br/>
	<div align="center">
			<a class="btn btn-primary btn-large" href="@Url.Content("../")">Go back</a>
	</div>
</div>

SKASP.WEB/Views/Home/Default.cshtml
@using SKASP.DOMAIN
@using SKASP.DOMAIN.EntitiesModel
@using SKASP.HELPERS
@model SKASP.DOMAIN.Abstract.IManageable<News>

@{
    ViewBag.Title = "Default";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<div>
	<div id="defaultCarousel" class="carousel slide">
		<div class="carousel-inner">
			<div align="center" class="item active">
				<img src="@Url.Content("../../Content/images/carousel/cr_img1.jpg")" />
				<div class="carousel-caption"></div>
			</div>
			<div class="item" align="center">
				<img src="@Url.Content("../../Content/images/carousel/cr_img2.jpg")" />
				<div class="carousel-caption"></div>
			</div>
			<div class="item" align="center">
				<img src="@Url.Content("../../Content/images/carousel/cr_img3.jpg")" />
				<div class="carousel-caption"></div>
			</div>
		</div>
		<a class="left carousel-control" data-slide="prev" href="#defaultCarousel"></a>
		<a class="right carousel-control" data-slide="next" href="#defaultCarousel"></a>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="hero-unit">
			<h1>Greetings you on my ASP.NET Blog! For Now with MVC</h1>
			<p>This technical blog I used for increased my skills in web design, development and etc.</p>      
			<p>You can find at this site:</p>
			<div>
				<div class="media">
					<a class="pull-left" href="#">
						<img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" src="@Url.Content("../../Content/images/icons/info.jpg")"/>
					</a>
					<div class="media-body">
						<h4 class="media-heading"></h4>
						<a class="label-info" href="@Url.Action("About")">Information About Me...</a>
					</div>
				</div>
				<div class="media">
					<a class="pull-left" href="#">
						<img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" src="@Url.Content("../../Content/images/icons/chat.png")"/>
					</a>
					<div class="media-body">
						<h4 class="media-heading"></h4>
						<a class="label-info" href="@Url.Action("Chat", "Chat")">Simple Chat, when you can ask me several questions...</a>
					</div>
				</div>
				<div class="media">
					<a class="pull-left" href="#">
						<img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" src="@Url.Content("../../Content/images/icons/rss.png")"/>
					</a>
					<div class="media-body">
						<h4 class="media-heading"></h4>
						<a class="label-info" href="@Url.Action("RSS", "RSS")">RSS Reader, when you can reead your favorite feeds...</a>
					</div>
				</div>
				<div class="media">
						<a class="pull-left" href="#">
							<img class="media-object" data-src="holder.js/64x64" alt="64x64" style="width: 64px; height: 64px;" src="@Url.Content("../../Content/images/icons/forum.png")"/>
						</a>
						<div class="media-body">
							<h4 class="media-heading"></h4>
							<a class="label-info" href="@Url.Action("Themes", "Forum")">Forum, where you can create youth problem topics...</a>
						</div>
				</div>
				<p>and a lot of other things...</p>
				<br/>
				<p>Wish you a lot of fun with my site...</p>
			</div>
			<p>
				<a class="btn btn-primary btn-large" href="@Url.Action("About", "Home")">Learn more &raquo;</a>
			</p>
		</div>
		<div id="NewsArray" class="label-success well">You can see @Model.Repository.Count() news on this site!			</div>
		@foreach (News news in Model.Repository)
		{
			@Html.NewsViewer(news)
		}
		<!--Html.RenderPartial("News", news);	-->
	</div>
</div>

@section onloader
{
	function() {
          			$('#defaultCarousel').carousel({
          				interval: 1000
          			});
          		}
}

SKASP.WEB/Views/Home/NewsViewer.cshtml
@model SKASP.DOMAIN.EntitiesModel.News

@{
	ViewBag.Title = "NewsViewer";
	Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div id="TitleDiv" class="label label-success" style="font-size: 23px; padding: 10px;">News Title: @Model.Name</div>
<br/>
<div id="DescrDiv" class="well well-large">Description: @Html.Raw(Model.NewsContent)</div>
<br/>
<div id="TimeDiv" class="label">Published Date: @Convert.ToDateTime(Model.Date).ToString("MM-dd-yyyy")</div>